# Generated by Django 4.1.2 on 2022-10-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlackUsers',
            new_name='SlackUser',
        ),
    ]
